### ISSUE TITLE
Add licence

### ISSUE THREAD

**Issue by mottosso** [71/scoop-better-shimexe#3]
Hi #71 (loving that username),

I found your project via the Scoop project, [here](https://github.com/lukesampson/scoop/issues/3294#issuecomment-480610504) and found it really useful in a separate but related project to create executables of Python "console_scripts" that has relative paths to the Python interpreter [here](https://github.com/mottosso/rez-pipz), as opposed to the absolute ones it creates per default.

I would like to ask if you could attach a permissive licence, such as MIT or better yet The Unlicence to your project such that I could bundle it alongside mine?

**Comment by 71** [comment]
Done, you can either use MIT or The Unlicense!

**Comment by mottosso** [comment]
Thanks!
