### ISSUE TITLE
Does not detect that the shim points to a GUI app

### ISSUE THREAD

**Issue by trajano** [71/scoop-better-shimexe#4]
Because it does not detect that it had started a gui app say PuTTY in my case https://github.com/lukesampson/scoop-extras/issues/2801#issuecomment-527587551 it leaves the window open and if you close the window it also closes the process.

Not sure if it will help but say you get the `HANDLE` from your `CreateProcess` perhaps use this method to see if the process is going to use GUI resources to detect if it is going to be a Windowed app or not  https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getguiresources

**Comment by 71** [comment]
Did you try to build the exe yourself? The `releases` page isn't up to date, and fixes for this specific case were pushed since then.

**Comment by trajano** [comment]
Nope. I don't have a VC++ environment set up.  Though perusing the code I am not sure if this will work on non-US machines because of the use of `A` at the end rather than `W` but that's another issue which I cannot test at the moment, but I don't want to forget it so I am just writing this down here quickly.

**Comment by 71** [comment]
That's a good concern I didn't think about. I use Hangul and French characters often and never had a problem until now, but maybe I was merely lucky. I'll compile it and upload it to the releases.

**Comment by trajano** [comment]
OK let me know I'll do the reshim thingy.  I am still in the middle of reinstalling VS since my installation got corrupted.

**Comment by 71** [comment]
The updated version is now in the releases.

I just tested with non-ASCII characters and there are indeed errors. I can't fix them right now, though.

**Comment by trajano** [comment]
No worries about the non-ASCII stuff.  I don't think we have any that need it yet :)

**Comment by trajano** [comment]
Just tested now with 1.1 still has the same issue as I had indicated earlier.

My test was to run it like

Win-R then `putty mysite`

**Comment by 71** [comment]
c38134eb91945a7af0bad9811d98711dc011eb9b fixes both the non-ASCII stuff and the console window problem. Thanks for your patience!
